### PR TITLE
Plugin changes for Paychex requirements

### PR DESCRIPTION
**Pull request by richgonzalez321**
Some of the changes made:

1)      Make RTC polling take load rules into consideration
2)      Enable plugin to accept new components when they are added after the workspace is created
3)      Automatically create the workspace when job runs if it doesn’t exist
4)      Make a global default for RTC repository
5)      Make username and password global settings
6)      Remove password from the console log
7)      Fix a bug where RTC plugin does not run accept command
8)      Remove the workspace name from the GUI, so it doesn’t have to be created manually – related to point 3
9)   Resolve variables in the workspace name NODE_NAME and JOB_NAME
10)   Make a default value for the workspace name (${NODE_NAME}_${JOB_NAME})
11)   Script to delete RTC workspaces after they are no longer needed (job was shelved)
12)   Fixed changes link on Jenkins job to display changesets accurately
13)   Have load command take load rules into consideration

### CODE REVIEW

**Comment by RoystonS** [comment]
There are some good changes in here, but I'm also seeing a number of problems with this merge/pull request:
- Moving the configuration of username + password from the job to global means that it's no longer possible to have job-specific user details
- Moving the configuration of username + password from the job to global means that all users upgrading to this version of the plugin will be forced to reconfigure their username and password details: it won't transfer configuratoin over.
- I can't see why this was done, but all of the JazzClient.findScmExecutable code was removed, forcing the plugin to find 'scm' on the path instead of trying to locate it relative to the configured file as it did before.
- The configurable timeout has been removed and replaced with a hardcoded one
- New environment variables (what do they do?) RTC_AGENTS_USING_COMMON_WORSPACE and RTC_COMMON_WORSPACE_UNC are misspelt.
- Most seriously: the accept command no longer provides the change set ids to RTC: this means that there's a race condition introduced between determining (and reporting) the set of changes and accepting the changes into the build.  (There is a unit test for this in AcceptCommandTest, but this set of changes commented it out.)

Should I raise separate issues for these?

**Comment by richgonzalez321** [comment]
Wow, that is quite a detailed review. Thanks for that.

I’d say 1, 3, and 4 could definitely use a issue raised. 5 is harmless but could have an issue raised. 2 is resolved by 1. And 6 I believe is not an issue.

1)      The username and password were removed at a time when we didn’t realize that we were going to submit this back to the community. So, I agree that it causes diminished capability and should be changed. I think there should be a global settings default then the option to configure it on a job by job basis. Like the way the RTC URL works.

2)      Being forced to reenter the username and password isn’t great but at least it is only once. Instead of for every job. If my suggestion in 1) is used then this problem goes away.

3)      Can you explain what JazzClient.findScmExecutable does? I think I might have lost some code accidentally due to branching off at an earlier version or something. I thought I had the most up to date version but maybe not. What is “the configured file”?

4)      I didn’t realize it was a configurable timeout. This might also have been lost in a branching version mistake.

5)      These new environment variables were intended to allow multiple slaves to use the same workspace on a shared file system in order to prevent the duplication of files (and the download of files at every slave). But this strategy failed I believe due to TFS source control requirements. The code was left in disabled in case we decided to revisit it. But it could certainly be removed.

6)      Previously the plugin reported change set ids which were session specific. Meaning that the number provided was no longer valid for another user or on a different day. Now I believe the plugin reports the date and time for the changeset so it can be looked up at least (realized afterward this was not your concern). There was a problem with the initial design in that if one slave had a workspace and accepted changesets 1 and 2. Then the next day a different slave executed the same Jenkins job and it has an older workspace it would accept changes 1 and 2 again. Which then would show in the changes page as if the changes were accepted multiple times. This was probably ok in a previous version when you were able to specify the repository workspace name, since the changes were repository workspace specific. But in order to prevent the work required to create a new repository workspace for every build job multiplied by every slave it might run on there was a change to the design so that the repository workspace is created dynamically. I think it is becoming clear to me what you mean by race condition. You believe the changeset list is being determined with one command and accepted with a different command. I’m going to have to disagree with that assessment if that is what you mean. If you refer to line 185 and line 206 of JazzSCM.java you will notice that the changes list that is displayed comes from the accept command, not the compare command. So, what is displayed as changes is what was accepted. Sorry if this point is a little rambling but all good information I think.

**Comment by RoystonS** [comment]
Thanks for that.

Re 1+2: Yes, I was imagining that global username+password as defaults plus optionally-overriding per-job username+password would be the way to go.  I'd actually started to implement that a little while ago, so I'd be happy to tweak it back in again.

Re 3: findScmExecutable is a little odd.  The idea is that you can configure the location of the tool to be either scm.exe or lscm (or lscm.bat).  lscm.bat is great because it starts up much faster because it launches a background daemon the first time. But sometimes you actually need to find the real scm.exe.  I have a local patch I'm planning to push up which will optionally kill that daemon when the job completes, but you need to run scm.exe (not lscm) in order to kill the daemon.  So most of the time you should use the configured tool location (and not a hardcoded 'scm') but other times it's good to run scm.exe directly.  If somebody has gone to the effort of providing a location for lscm, we should look for scm.exe there before having to resort to the system path.  (I'm happy to configure Jenkins to tell it where to find tools, but I don't really want to be modifying the system path to do that. It's a bit global, and a pain with lots of slaves.)

Re: 4: yep, the timeout was configurable.  Yes, I thought it looked like a merge gone wrong somewhere. :-)

Re: 5: yep, probably good to remove dead code, but by no means urgent.

Re: 6: ah, I see you changed the way it worked so it _no longer_ runs the separate compare + accept calls - sorry, hadn't spotted that.  I'm completely paranoid about accurate build reporting and reproducibility. :-)

Unfortunately it looks like I can't raise issues in this particular repo - presumably because it's a fork rather than the master one. Not sure how to change that.

I'll get on and do the username+password defaulting as I've almost got that here anyway, and raise a pull request for that. I'm happy to put the rest in too as we actively use those.

**Comment by richgonzalez321** [comment]
I believe the pull request was merged into the master. Can you put the ticket against the master?

I’ll trust you on 3) but I think there is a global setting where you can specify the location of the scm.exe. We use a UNC path in there and don’t put scm.exe on that path at all. Also just as a side note we had an issue getting lscm.bat to work. Don’t remember what it was but we had to switch to scm.exe. In global config it’s “Jazz command line executable”.

By the way there is some problems with running this plugin on Linux which we are currently looking into.

The information contained in this message may be privileged, confidential and protected from disclosure. If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify your representative immediately and delete this message from your computer. Thank you.

**Comment by RoystonS** [comment]
The pull was merged into the master in this repo, not the original deluan one where the issues lie.

Re: 3: yes, there's a setting for the location, but I used to be able to specify lscm.bat in there. The plugin automatically switched to scm.exe when necessary. (That was the findScmExecutable logic.)

I'm almost done with the per-job username + password and timeout stuff. Hoping to get that in today, but we'll  have to see.

I've also spotted a lot of very specific code added to JazzSCM to do with 'controllers' and resolving workitems. Looks like something custom to your installation that we probably want to take out (or generalise) in a public plugin. It's the stuff in JazzSCM#checkout that deals with 'RTCWorkItemLinker\run2.bat' and then calls updateWorkItems again to call some specific tool that I'm guessing only you have?

**Comment by richgonzalez321** [comment]
The workitem update stuff is specific to our installation. I think there was a desire to make our version consistent with the public one so that we don’t have to modify the source every time we upgrade. But your point makes sense if it isn’t code anyone else can use it shouldn’t be in the public version. Feel free to remove it. And I’ll just have to add it back in each time we upgrade or come up with a way to make it work for the general public. The problem with including that feature in the plugin is that it requires a lot of jar files from RTC. Maybe I can add a generic external reporting tool hook that other people can use with any script or tool they want.

It is good to see someone else pushing the plugin forward. Development had slowed to a crawl when we decided to start using it.

The information contained in this message may be privileged, confidential and protected from disclosure. If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify your representative immediately and delete this message from your computer. Thank you.

**Comment by RoystonS** [comment]
I just submitted pull request #11 to restore the job-specific username, password and repository information (with sensible defaulting).  I'll follow up with some of the others, but I wanted to keep a fairly tight set of changes.  I'd value a review of that set of changes if you could?

**Comment by RoystonS** [comment]
Hi again.  I've just checked JazzClient and I _think_ that race condition I mentioned earlier (item 6 in my original list) _is_ actually there.  JazzSCM does indeed use the result of JazzClient.accept() to report the changes. However, JazzClient.accept() itself does a compare, and then runs the real accept if there were some changes, but it actually returns the changesets from the compare, not the accept.  Am I going mad, or is that what it's actually doing?

**Comment by richgonzalez321** [comment]
You're right. Last time I didn't dig deep enough. There is one other variable here which is irrelevant but still interesting to note. On line 193-194 of JazzSCM.java:

List<JazzChangeSet> changes2 = updateWorkItems(build, listener, client);
if (changes2 != null) changes = changes2;

The changes get modified by the updateWorkItems function. This was meant to make those changes accurate but  that functionality only goes into effect when the run2.bat program is available. Which is only in my local installation. Also, I'm thinking now that even that doesn't resolve the race condition. Argh.

Now that I think about it even if I had made the changes list generated from the accept command (or the compare command for that matter) that would only introduce a new error. Those commands will return what that specific repository workspace has for changes. But that is different for every slave because the last time each slave has done an accept is different. Really what you want to know is what changes have happened since the last time this project has built, regardless of which slave it built on.

So, what was done in the updateWorkItems function was to query the RTC server using the RTC Java API and ask "what changesets have been put in since this date and time?". That works up to a point. I am using it to get the changes since the last build but it leaves a hole where a changeset that has been committed between the time the accept command runs and the RTC API is invoked would be included in the changes list when it shouldn't be. This could be resolved by comparing what was accepted with what was retrieved by the RTC API and removing anything that is newer than the newest thing accepted (or something approximately like that). There is one glaring problem with this strategy: the RTC plugin doesn't have access to the RTC Java API. Short of distributing the RTC Java API as a separate multi-megabyte package I'm not sure how to resolve that. Perhaps RTC has a REST API or something that can be used for that purpose.

**Comment by RoystonS** [comment]
Is there a problem with using a single workspace for a job, and using it across all the build nodes?  Does your cross-session issue only appear when you start creating workspaces per build node?

Using a single workspace for a job 'just works', doesn't it, because you're asking what's changed relative to a workspace which corresponds to the last build of that job?  (I'm probably missing something here.)

**Comment by RoystonS** [comment]
(Btw, the IBM Rational team are working on an official integrated plugin due some time later in the year, so it's probably not worth embarking on a big API rework job.)

**Comment by richgonzalez321** [comment]
I believe there is a problem with using a single workspace for a job. This only works if you only allow your job to run on a single slave. Which is fine for some people, but not always ideal. The reason this is a problem is the RTC server believes the local sandbox is the same as the repository workspace. So here is an example of the problem:

Slave 1 builds job A
Slave 2 then builds job A
Slave 1 on a later date accepts some changes
Slave 2 (using the same repository workspace as slave 1) now wants to look for changes and the RTC server says "no changes you accepted them all already". Of course Slave 2 has done no such thing, it was Slave 1 that accepted the changes. So now Slave 2 is out of sync. Or if there are additional changes after Slave 1 did his accept then Slave 2 will attempt to accept the additional changes but not the original ones. Things get weird quick.

Hope that made sense but in the end its a rule that every local workspace is mapped to one repository workspace and vice versa.

**Comment by RoystonS** [comment]
Hmm.  That's pretty sad if true.  I'll investigate to see if there's a workaround for that.

In the meantime, there's a fairly simple solution:  One feature I was planning to add was the ability to take snapshots at the time of each build, so you can always get back from a particular build number to the exact source you used.  If you're doing that, it's easy to get build diffs - even across build nodes - you just compare the build snapshots rather than trying to compare against a rolling workspace. But I can imagine that some people wouldn't _want_ such snapshots created with every build, which is a bit of a problem.

**Comment by RoystonS** [comment]
I've thought about it a bit more, and my understanding of how accepts work with regard to repository workspaces doesn't quite match the conclusion you got in your scenario.   I could _well_ be completely wrong in my understanding.

With your scenario with a single shared repository workspace across multiple nodes:

Slave 1 builds job A
Slave 2 then builds job A
Slave 1 on a later date accepts some changes G, H and I
Slave 2 looks for changes, (it's comparing the repository workspace [not its disk] against the backing stream) and if there are some, it accepts the new changes into the repository workspace and then loads that workspace onto disk.

So, with your scenario, whilst Slave 2 has not done the accept of the earlier changes onto _its disk_, Slave 1 did accept the changes into the repository workspace (which really lives on the server).  So when Slave 2 comes along, it accepts more changes into the (server-residing) repository workspace.   Remember that you can accept changes from a stream into a workspace without ever fetching a single file onto disk: the accept happens in the workspace on the server.

I _think_ that the only time the identity of the nodes comes into it is when you actually load the repository workspace onto your local disk.  I think the only problem you might get is if there's a funny optimization during the load phase where it thinks it knows what's on disk for a particular node, but gets the diffs wrong.

Have I got it wrong?

**Comment by richgonzalez321** [comment]
I still think this won't work, but maybe there is a way to work around the problem that I'm not aware of. And you should know that RTC representatives said when I asked them said to only use one sandbox per repository workspace.

I think your description is accurate except you left out one step which is that when the repository workspace and the stream are synced there is a syncing with the local sandbox as well. This might be avoided by deleting the local sandbox every run but then you lose the "Use Update" feature. When Slave 2 tries to do the accept it can't accept the "more changes" because RTC identifies that the sandbox is out of sync already. But at this point it is all pretty hypothetical, I wasn't able to find a log of when I attempted this scenario but I just ran it again like this:

scm create workspace acceptWorkspace1 -r https://<myRTCURL>:9443/ccm -u <myRTCUserName> -P <myRTCPassword> -s <myRTCStreamName>

scm load acceptWorkspace1 -r https://<myRTCURL>:9443/ccm -d first

scm load acceptWorkspace1 -r https://<myRTCURL>:9443/ccm -d second

scm load acceptWorkspace1 -r https://<myRTCURL>:9443/ccm -d third

cd first

notepad CopyArtifacts.groovy
    change and save the file

scm checkin .

scm changeset comment 9054 "Test accept"

scm deliver

cd ..

cd second

scm status
Password (<myRTCUserName> @ https://<myRTCURL>:9443/ccm):
 Workspace: (9053) "acceptWorkspace1" <-> (6529) "<myRTCStreamName>"
  Component: (1053) "EBA" <-> (6529) "<myRTCStreamName>"
    Baseline: (8999) 3 "2.19.2013"
  Some components in (9053) "acceptWorkspace1" are out of sync.
    (1053) "EBA"

scm accept

Password (<myRTCUserName> @ https://<myRTCURL>:9443/ccm):
 Workspace unchanged.

notepad CopyArtifacts.groovy
    change was not accepted

That's not to say this can't be worked around. I just don't know how to or if it is possible. Let me know if you get the same result.

**Comment by RoystonS** [comment]
Heh.  In my local copy of the RTC plugin I have an option to completely wipe down the workspace each build: that way we absolutely know for sure that there aren't any bits left behind from a previous build and we can absolutely guarantee clean builds.  So I'd be loading the workspace from scratch anyway.

I just can't really see a way that an in-place accept/update is compatible with multiple nodes with the out-of-the box tools.

What if you did an explicit 'scm load' in the sandbox after doing the accept?  Wouldn't that force the sandbox to update with respect to the actual workspace contents?

**Comment by richgonzalez321** [comment]
Doesn't look like it:

scm load acceptWorkspace1 -r https://<myRTCURL>:9443/ccm -d .
Problem running 'load':
Must load in sandbox root (C:\acceptProblem\second). To load into a descendent specify the path with target. Try 'scm help load' for more information.

I just don't think RTC is built to handle more than one sandbox per repository workspace. Just need to create a new one per agent. The problem to solve, to me, is how to get the accurate changes. Which I think can be done. It's just not easy. Comparing the accept results to the list of all changes since last build.

**Comment by RoystonS** [comment]
I'm checking with some of our RTC DevOps guys. I've definitely been told previously that the sandbox<->repository link was looser than this. :-(

**Comment by RoystonS** [comment]
I just tried your above scenario, with an explicit load run from _outside_ the sandbox and I got it to work without problems.

I created first, second, third directories, just like you.  When I did an 'scm status' in a sandbox that was out of sync, it actually told me, and suggested how to fix it up.

C:\second>scm status
Workspace: (1039) "acceptWorkspace1" <-> (1032) "VAM_Sandbox_Stream"
  Component: (1017) "VAM_Sandbox"
    Baseline: (1033) 2 "Initial import"
  Some components in (1039) "acceptWorkspace1" are out of sync.
    (1017) "VAM_Sandbox"
Local file system is out of sync. Run 'scm load' with --force option to reload >

cd ..
C:> scm load acceptWorkspace1 -r dev -d second --force
Successfully loaded items into the sandbox.

The 'second' directory then happily contains the expected contents.

Could you try running that 'load' in the parent directory to 'second', i.e. the same place you originally ran the three initial 'scm load' commands from?

**Comment by richgonzalez321** [comment]
Very nice. I got it to work. So, I was using client version 2.0 which isn't able to do the force. I upgraded to 3.0, which was again unable to do the force. Then I upgraded to the client that comes with RTC4 (client version 3.1) and it worked. Our RTC server is at version 4.

So it looks like this might enable a single repository workspace for multiple agents. This version of RTC client didn't exist when I looked into this (and RTC told me to stick to one sandbox per repository workspace). That could be a nice improvement if it works. Although, do need to keep in mind the people using older versions of RTC. Don't want to disable them.

**Comment by richgonzalez321** [comment]
I also wonder, does the force cause a redownload of all the files. In which case again we are defeating "Use Update". Which is unfortunate for those workspaces that take a long time to load.

**Comment by RoystonS** [comment]
Interesting. The documentation for v2 does list '--force' as an option: http://pic.dhe.ibm.com/infocenter/rtc/v2r0m0/index.jsp?topic=/com.ibm.team.scm.doc/topics/r_scm_cli_load.html

I'll see about getting some older client versions, but in the meantime, is --force not listed when you do an 'scm help load' ?

**Comment by richgonzalez321** [comment]
It is listed but was not actually accepted when attempted. Unless I did something wrong. Your copy paste of the result of scm status shows a note suggesting to use force but I didn't get that with the older versions. Also, using force with the older versions did the usual failure. So not sure where the difference is. Sounds like you are on to something though:

scm load acceptWorkspace1 -r https://rtcURL:9443/ccm -d second --force
Problem running 'load':
Must load in sandbox root (second). To load into a descendent specify the path with target. Try 'scm help load' for more information.

Help on load
Load the contents of the specified workspace into the local filesystem. By default, the workspace is loaded into a subdirectory of the current working directory named the same as the provided workspace selector.

Usage: scm load [options] <ws-name> [remote-path...]
  ws-name     - Workspace to load (name[@repo], alias, or UUID[@repo]).
  remote-path - List of remote items to load, may be a component (name, alias, o
r UUID), or a remote path within a component.

Options:
  --all                        - Selects all components. Priority is given to explicitely selected components in the case of a conflict.
  --certificate arg            - The file containing the user's login certificate.
  --smartCard                  - Use the connected smart card for authentication
.
  -a [--alternative-name] arg  - Alternative name for the item specified in remote-path.
  -d [--dir] arg               - Root directory to save files to.
  -f [--force]                 - Overwrite files that already exist in the filesystem.
  -i [--include-root]          - Load component roots as directories in the filesystem.
  -L [--local-rules] arg       - Local path to load rules. Must be specified with exactly one component.
  -P [--password] arg          - Password for repository.
  -q [--quiet]                 - Print the minimum of output during normal operation.
  -r [--repository-uri] arg    - URI specifying the location of repository.
  -R [--remote-rules] arg      - Path to the load rules within a component. Must be specified with exactly one component.
  -t [--target] arg            - Optional local path where changes should be loaded
  -u [--username] arg          - Username for repository.

**Comment by richgonzalez321** [comment]
My bad that scm help load paste was from client 3.1. But I just ran the other two client versions and they both also had the force option.

**Comment by RoystonS** [comment]
I think I might have a cunning plan for making that stuff work.  More on that later.

I'm just trying to restore a couple of bugfixes that the patch removed (to do with finding the exe correctly and using the correct character encoding) and I'm struggling to understand your AcceptCommand#processLoadRules method.  (I don't yet use load rules so it's hard to try out):

It seems to spend a good amount of time calculating a value for commandData, but then never actually uses it, instead seemingly returning a call out to a .bat file instead? Am I missing something?

**Comment by richgonzalez321** [comment]
You don't need to setup load rules at all in your project to use load rules. All load rules means is "don't get all the files. Just give me these specified folders".

As far as the processLoadRules method. The way the plugin was designed each Command.java subclass only executes one command on the command prompt. scm load, scm history, etc. So when I went to add load rules I came to a problem. You can only use load rules against one component when executing a command. Any stream with more than one component cannot be used with load rules. To work around this problem I needed to execute load at least once per component (although the design is to execute it once per load rule to keep it simple). Since the Command.java doesn't allow scm load to be executed more than once I created a bat file which will be the command instead of scm.exe. So I can execute one command, the batch file, and get multiple scm.exe load commands run. Because load is used more than once accept has to be used more than once...

The commandData isn't executed in AcceptCommand. It just builds the content of the batch file which is executed later in joinWithTimeout or something like that.

Although, because it is a batch file that function doesn't work in Linux. Which is why we have rewritten that method already in our environment. We are giving it some time to test before submitting it back to github. The new design allows AcceptCommand and LoadCommand to have more than one command in it. That way they can be run for each line in the load rules without needing a batch or shell script.

**Pull request merged**
